export default {
  GET_MEMBER: 'GET_MEMBER',

  GET_DEVICES: 'GET_DEVICES',

  GET_RECORDS: 'GET_RECORDS',
  ADD_RECORD: 'ADD_RECORD',
  REMOVE_RECORD: 'REMOVE_RECORD',

  CHECK_DEVICE: 'CHECK_DEVICE',
  UNCHECK_DEVICE: 'UNCHECK_DEVICE',
  UNCHECK_ALL_DEVICES: 'UNCHECK_ALL_DEVICES',
};
