export default {
  GET_MEMBER: 'GET_MEMBER',
  GET_MEMBERS: 'GET_MEMBERS',

  GET_DEVICES: 'GET_DEVICES',
  UPDATE_DEVICES: 'UPDATE_DEVICES',

  GET_RECORDS: 'GET_RECORDS',
  ADD_RECORD: 'ADD_RECORD',
  REMOVE_RECORD: 'REMOVE_RECORD',

  CHECK_DEVICE: 'CHECK_DEVICE',
  UNCHECK_DEVICE: 'UNCHECK_DEVICE',
  UNCHECK_ALL_DEVICES: 'UNCHECK_ALL_DEVICES',

  GET_APPLICATIONS: 'GET_APPLICATIONS',
  PUSH_APPLICATION: 'PUSH_APPLICATION',
  POP_APPLICATION: 'POP_APPLICATION',
  UPDATE_APPLICATION: 'UPDATE_APPLICATION',
};
